apiVersion: v1
kind: Secret
metadata:
  name: lldap-secret
  namespace: lldap
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: "jwt-secret,key-seed,admin-pass"
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "authelia"