apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: user-config
spec:
  secretTemplate:
    type: Opaque
    stringData:
      password: $(value)
      user.json: |
        {
          "id": "aaron",
          "email": "aaron@lab53.net",
          "password": "$(value)"
        }