apps:
  - name: traefik
  - name: troubleshooting
  - name: ladder
  - name: local-path-provisioner
  - name: kubernetes-secret-generator
  - name: cloud-native-postgres
    namespace: cnpg-system
    serverSideApply: true
  - name: immich
