apps:
  - name: local-path-provisioner
  - name: traefik
  - name: cloud-native-postgres
    namespace: cnpg-system
    serverSideApply: true
  - name: immich
  - name: ladder
  - name: lldap
  - name: authelia
  - name: traefik-external
  - name: secretgen-controller
  - name: transmission
  - name: calibre-web-automated
    namespace: cwa
