apps:
  - name: local-path-provisioner
  - name: traefik
  - name: cloud-native-postgres
    namespace: cnpg-system
    serverSideApply: true
  - name: immich
  - name: ladder
  - name: lldap
  - name: authelia
    ignoreDifferences:
      - kind: Secret
        name: authelia
        jsonPointers:
          - /data
      - group: apps
        kind: Deployment
        name: authelia
        jsonPointers:
          - /spec/template/metadata/annotations/authelia.com~1checksum-secret
  - name: traefik-external
  - name: secretgen-controller
  - name: transmission
  - name: calibre-web-automated
    namespace: cwa
