apps:
  - name: local-path-provisioner
  - name: traefik
  - name: cloud-native-postgres
    namespace: cnpg-system
    serverSideApply: true
  - name: immich
  - name: ladder
  - name: lldap
    targetRevision: feat/ocis
  - name: authelia
    targetRevision: feat/ocis
  - name: traefik-external
  - name: secretgen-controller
  - name: transmission
  - name: calibre-web-automated
    namespace: cwa
  - name: dynamic-dns
  - name: jellyfin
  - name: argo-config
  - name: ocis
    targetRevision: feat/ocis
