apps:
  - name: local-path-provisioner
  - name: reflector
  - name: kubernetes-secret-generator
  - name: traefik
  - name: cloud-native-postgres
    namespace: cnpg-system
    serverSideApply: true
  - name: immich
  - name: ladder
  - name: lldap
  - name: authelia
  - name: traefik-external