apps:
  - name: local-path-provisioner
  - name: traefik
  - name: cloud-native-postgres
    namespace: cnpg-system
    serverSideApply: true
  - name: immich
  - name: ladder
  - name: lldap
  - name: authelia
  - name: traefik-external
  - name: secretgen-controller
  - name: transmission
  - name: calibre-web-automated
    namespace: cwa
  - name: dynamic-dns
  - name: jellyfin
  - name: argo-config
  - name: metallb
    namespace: metallb-system
    ignoreDifferences:
      - group: "apiextensions.k8s.io"
        kind: CustomResourceDefinition
        name: bgppeers.metallb.io
        jsonPointers:
          - /spec/conversion/webhook/clientConfig/caBundle
      - group: "apiextensions.k8s.io"
        kind: CustomResourceDefinition
        name: addresspools.metallb.io
        jsonPointers:
          - /spec/conversion/webhook/clientConfig/caBundle
  - name: ocis
