table:
  name: privacy_settings
  schema: public
array_relationships:
  - name: activities
    using:
      foreign_key_constraint_on:
        column: privacy_setting_id
        table:
          name: activities
          schema: public
  - name: lists
    using:
      foreign_key_constraint_on:
        column: privacy_setting_id
        table:
          name: lists
          schema: public
  - name: prompts
    using:
      foreign_key_constraint_on:
        column: privacy_setting_id
        table:
          name: prompts
          schema: public
  - name: user_books
    using:
      foreign_key_constraint_on:
        column: privacy_setting_id
        table:
          name: user_books
          schema: public
  - name: users
    using:
      foreign_key_constraint_on:
        column: account_privacy_setting_id
        table:
          name: users
          schema: public
  - name: users_by_activity
    using:
      foreign_key_constraint_on:
        column: activity_privacy_settings_id
        table:
          name: users
          schema: public
select_permissions:
  - role: guest
    permission:
      columns:
        - id
        - setting
      filter: {}
  - role: owner
    permission:
      columns:
        - id
        - setting
      filter: {}
