table:
  name: notification_settings
  schema: public
object_relationships:
  - name: user
    using:
      manual_configuration:
        column_mapping:
          user_id: id
        insertion_order: null
        remote_table:
          name: users
          schema: public
insert_permissions:
  - role: owner
    permission:
      check:
        user_id:
          _eq: X-Hasura-User-Id
      columns:
        - channel_ids
        - notification_type_id
        - user_id
select_permissions:
  - role: owner
    permission:
      columns:
        - id
        - notification_type_id
        - user_id
        - channel_ids
      filter:
        user_id:
          _eq: X-Hasura-User-Id
      limit: 100
update_permissions:
  - role: owner
    permission:
      columns:
        - channel_ids
      filter:
        user_id:
          _eq: X-Hasura-User-Id
      check:
        user_id:
          _eq: X-Hasura-User-Id
