---
# Source: authelia/templates/secret.yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: authelia
  labels: 
    app.kubernetes.io/name: authelia
    app.kubernetes.io/instance: authelia
    app.kubernetes.io/version: 4.39.1
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: authelia-0.10.4
data:
---
# Source: authelia/templates/configMap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia
  labels: 
    app.kubernetes.io/name: authelia
    app.kubernetes.io/instance: authelia
    app.kubernetes.io/version: 4.39.1
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: authelia-0.10.4
data:
  configuration.yaml: |
    ---
    # yaml-language-server: $schema=https://www.authelia.com/schemas/v4.39/json-schema/configuration.json
    theme: 'dark'
    default_2fa_method: 'totp'
    server:
      address: 'tcp://0.0.0.0:9091/'
      asset_path: ''
      headers:
        csp_template: ''
      buffers:
        read: 4096
        write: 4096
      timeouts:
        read: '6 seconds'
        write: '6 seconds'
        idle: '30 seconds'
      endpoints:
        enable_pprof: false
        enable_expvars: false
        authz:
          auth-request:
            implementation: 'AuthRequest'
          ext-authz:
            implementation: 'ExtAuthz'
          forward-auth:
            implementation: 'ForwardAuth'
    log:
      level: 'info'
      format: 'text'
      file_path: ''
      keep_stdout: true
    telemetry:
      metrics:
        enabled: false
    identity_validation:
      elevated_session:
        code_lifespan: '5 minutes'
        elevation_lifespan: '10 minutes'
        characters: 8
        require_second_factor: false
        skip_second_factor: false
      reset_password:
        jwt_lifespan: '5 minutes'
        jwt_algorithm: 'HS256'
    totp:
      disable: false
      issuer: 'Authelia'
      skew: 1
      secret_size: 32
      algorithm: 'SHA1'
      digits: 6
      period: 30
      allowed_algorithms:
        - 'SHA1'
      allowed_digits:
        - 6
      allowed_periods:
        - 30
    webauthn:
      disable: false
      enable_passkey_login: false
      display_name: 'Authelia'
      attestation_conveyance_preference: 'indirect'
      timeout: '60 seconds'
      filtering:
        permitted_aaguids: []
        prohibited_aaguids: []
        prohibit_backup_eligibility: false
      selection_criteria:
        attachment: ''
        discoverability: 'preferred'
        user_verification: 'preferred'
      metadata:
        enabled: false
        validate_trust_anchor: true
        validate_entry: true
        validate_entry_permit_zero_aaguid: false
        validate_status: true
        validate_status_permitted: []
        validate_status_prohibited: []
    ntp:
      address: 'udp://time.cloudflare.com:123'
      version: 4
      max_desync: '3 seconds'
      disable_startup_check: false
      disable_failure: false
    authentication_backend:
      password_reset:
        disable: false
        custom_url: ''
      password_change:
        disable: false
      ldap:
        implementation: 'lldap'
        address: 'ldap://lldap.lldap:3890'
        timeout: '5 seconds'
        start_tls: false
        tls:
          server_name: ''
          skip_verify: false
          minimum_version: 'TLS1.2'
          maximum_version: 'TLS1.3'
        pooling:
          enable: false
          count: 5
          retries: 2
          timeout: '10 seconds'
        base_dn: 'DC=lab53,DC=net'
        additional_users_dn: 'OU=people'
        additional_groups_dn: 'OU=Groups'
        group_search_mode: 'filter'
        permit_referrals: false
        permit_unauthenticated_bind: false
        permit_feature_detection_failure: false
        user: 'UID=admin,OU=people,DC=lab53,DC=net'
        attributes:
          distinguished_name: ''
          username: ''
          display_name: ''
          family_name: ''
          given_name: ''
          middle_name: ''
          nickname: ''
          gender: ''
          birthdate: ''
          website: ''
          profile: ''
          picture: ''
          zoneinfo: ''
          locale: ''
          phone_number: ''
          phone_extension: ''
          street_address: ''
          locality: ''
          region: ''
          postal_code: ''
          country: ''
          mail:  ''
          member_of:  ''
          group_name:  ''
    password_policy:
      standard:
        enabled: false
        min_length: 8
        max_length: 0
        require_uppercase: false
        require_lowercase: false
        require_number: false
        require_special: false
      zxcvbn:
        enabled: false
        min_score: 0
    session:
      name: 'authelia_session'
      same_site: 'lax'
      inactivity: '5 minutes'
      expiration: '1 hour'
      remember_me: '1 month'
      cookies:
        - domain: 'lab53.net'
          authelia_url: 'https://auth.lab53.net'
      redis:
        host: 'redis-master'
        port: 6379
        database_index: 0
        maximum_active_connections: 8
        minimum_idle_connections: 0
    regulation:
      modes:
      - 'user'
      max_retries: 3
      find_time: '2 minutes'
      ban_time: '5 minutes'
    storage:
      postgres:
        address: 'tcp://authelia-cluster-rw:5432'
        servers: []
        timeout: '5 seconds'
        database: 'authelia'
        schema: 'public'
        username: 'authelia'
    notifier:
      disable_startup_check: false
      filesystem:
        filename: '/config/notification.txt'
    identity_providers:
      oidc:
        lifespans:
          access_token: '1 hour'
          authorize_code: '1 minute'
          id_token: '1 hour'
          refresh_token: '1 hour and 30 minutes'
        enforce_pkce: 'public_clients_only'
        enable_pkce_plain_challenge: false
        enable_client_debug_messages: false
        enable_jwt_access_token_stateless_introspection: false
        minimum_parameter_entropy: 8
        discovery_signed_response_alg: ''
        discovery_signed_response_key_id: ''
        require_pushed_authorization_requests: false
        jwks:
          - algorithm: 'RS256'
            use: 'sig'
            key: {{ secret "/secrets/oidc-jwk-keypair/oidc-private-key" | mindent 10 "|" | msquote }}
        cors:
          allowed_origins_from_client_redirect_uris: false
        clients:
          - client_id: 'tailscale'
            client_name: 'Tailscale SSO'
            client_secret: '$pbkdf2-sha512$310000$RM0fzKMw38RxttTvALU3Tw$mWgP4QVLbQieihN99TfL8utB7VOpFof1Xfd70AoNBqlPlmxsTie9Xu53kyP/DQWMW3tZFXtZn57kKnzfW41YiQ'
            public: false
            redirect_uris:
              - 'https://login.tailscale.com/a/oauth_response'
            scopes:
              - 'openid'
              - 'email'
              - 'profile'
            grant_types:
              - 'authorization_code'
            response_types:
              - 'code'
            authorization_policy: 'two_factor'
            consent_mode: 'auto'
            require_pushed_authorization_requests: false
            require_pkce: false
            pkce_challenge_method: ''
            authorization_signed_response_alg: 'none'
            authorization_signed_response_key_id: ''
            authorization_encrypted_response_key_id: ''
            authorization_encrypted_response_alg: ''
            authorization_encrypted_response_enc: ''
            id_token_signed_response_alg: 'RS256'
            id_token_signed_response_key_id: ''
            id_token_encrypted_response_key_id: ''
            id_token_encrypted_response_alg: ''
            id_token_encrypted_response_enc: ''
            access_token_signed_response_alg: 'none'
            access_token_signed_response_key_id: ''
            access_token_encrypted_response_key_id: ''
            access_token_encrypted_response_alg: ''
            access_token_encrypted_response_enc: ''
            userinfo_signed_response_alg: 'none'
            userinfo_signed_response_key_id: ''
            userinfo_encrypted_response_key_id: ''
            userinfo_encrypted_response_alg: ''
            userinfo_encrypted_response_enc: ''
            introspection_signed_response_alg: 'none'
            introspection_signed_response_key_id: ''
            introspection_encrypted_response_key_id: ''
            introspection_encrypted_response_alg: ''
            introspection_encrypted_response_enc: ''
            introspection_endpoint_auth_method: 'client_secret_basic'
            introspection_endpoint_auth_signing_alg: 'RS256'
            request_object_signing_alg: ''
            request_object_encryption_alg: 'none'
            request_object_encryption_enc: ''
            token_endpoint_auth_method: 'client_secret_basic'
            token_endpoint_auth_signing_alg: ''
            revocation_endpoint_auth_method: 'client_secret_basic'
            revocation_endpoint_auth_signing_alg: 'RS256'
            pushed_authorization_request_endpoint_auth_method: 'client_secret_basic'
            pushed_authorization_request_endpoint_auth_signing_alg: 'RS256'
    access_control:
      default_policy: 'deny'
      rules:
        - policy: two_factor
          domain:
            - '*.lab53.net'
    ...
---
# Source: authelia/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: authelia
  labels: 
    app.kubernetes.io/name: authelia
    app.kubernetes.io/instance: authelia
    app.kubernetes.io/version: 4.39.1
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: authelia-0.10.4
spec:
  type: ClusterIP
  sessionAffinity: None
  selector:
    app.kubernetes.io/name: authelia
    app.kubernetes.io/instance: authelia
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
---
# Source: authelia/templates/deployment.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: authelia
  labels: 
    app.kubernetes.io/name: authelia
    app.kubernetes.io/instance: authelia
    app.kubernetes.io/version: 4.39.1
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: authelia-0.10.4
spec:
  selector:
    matchLabels: 
      app.kubernetes.io/name: authelia
      app.kubernetes.io/instance: authelia
  revisionHistoryLimit: 5
  minReadySeconds: 0
  updateStrategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 25%
  template:
    metadata:
      labels: 
        app.kubernetes.io/name: authelia
        app.kubernetes.io/instance: authelia
        app.kubernetes.io/version: 4.39.1
        app.kubernetes.io/managed-by: Helm
        helm.sh/chart: authelia-0.10.4
      annotations:
        authelia.com/checksum-config: 49095c682af9a2809b826856c8b7c9c6088bafbd609156fcede0a49b9dd8cfe8
        authelia.com/checksum-secret: e840301a49a6e60da06d51b8fb7aba2c021117a2d2911fa8c92d758f9259fc1d
    spec:
      hostNetwork: false
      hostPID: false
      hostIPC: false
      affinity: 
        nodeAffinity: {}
        podAffinity: {}
        podAntiAffinity: {}
      enableServiceLinks: false
      containers:
      - name: authelia
        image: ghcr.io/authelia/authelia:4.39.1
        imagePullPolicy: IfNotPresent
        command:
        - 'authelia'
        resources: 
          limits: {}
          requests: {}
        env:
        - name: AUTHELIA_SERVER_DISABLE_HEALTHCHECK
          value: "true"
        - name: AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE
          value: '/secrets/jwt-hmac-secret/jwt-hmac-secret'
        - name: AUTHELIA_SESSION_SECRET_FILE
          value: '/secrets/session-encryption-key/encryption-key'
        - name: AUTHELIA_SESSION_REDIS_PASSWORD_FILE
          value: '/secrets/redis-password/redis-password'
        - name: AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE
          value: '/secrets/admin-pass/lldap-admin-password'
        - name: AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE
          value: '/secrets/storage-encryption-key/encryption-key'
        - name: AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE
          value: '/secrets/postgres-creds/postgres-password'
        - name: AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET_FILE
          value: '/secrets/oidc-hmac-secret/oidc-hmac-secret'
        - name: X_AUTHELIA_CONFIG
          value: '/configuration.yaml'
        - name: X_AUTHELIA_CONFIG_FILTERS
          value: template
        startupProbe:
          failureThreshold: 6
          httpGet:
            path: /api/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /api/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /api/health
            port: http
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        ports:
        - name: http
          containerPort: 9091
          protocol: TCP
        volumeMounts:
        - mountPath: /config
          name: authelia
          readOnly: false
        - mountPath: /configuration.yaml
          name: config
          readOnly: true
          subPath: configuration.yaml
        - mountPath: /secrets/internal
          name: secrets
          readOnly: true
        - mountPath: /secrets/admin-pass
          name: secret-admin-pass
          readOnly: true
        - mountPath: /secrets/jwt-hmac-secret
          name: secret-jwt-hmac-secret
          readOnly: true
        - mountPath: /secrets/oidc-hmac-secret
          name: secret-oidc-hmac-secret
          readOnly: true
        - mountPath: /secrets/oidc-jwk-keypair
          name: secret-oidc-jwk-keypair
          readOnly: true
        - mountPath: /secrets/postgres-creds
          name: secret-postgres-creds
          readOnly: true
        - mountPath: /secrets/redis-password
          name: secret-redis-password
          readOnly: true
        - mountPath: /secrets/session-encryption-key
          name: secret-session-encryption-key
          readOnly: true
        - mountPath: /secrets/storage-encryption-key
          name: secret-storage-encryption-key
          readOnly: true
      volumes:
      - name: authelia
        emptyDir:
          sizeLimit: 100Mi
      - name: config
        configMap:
          name: authelia
          items:
          - key: configuration.yaml
            path: configuration.yaml
      - name: secrets
        secret:
          secretName: authelia
          items:
      - name: secret-admin-pass
        secret:
          secretName: admin-pass
          items:
          - key: password
            path: lldap-admin-password
      - name: secret-jwt-hmac-secret
        secret:
          secretName: jwt-hmac-secret
          items:
          - key: password
            path: jwt-hmac-secret
      - name: secret-oidc-hmac-secret
        secret:
          secretName: oidc-hmac-secret
          items:
          - key: password
            path: oidc-hmac-secret
      - name: secret-oidc-jwk-keypair
        secret:
          secretName: oidc-jwk-keypair
          items:
          - key: key.pem
            path: oidc-private-key
      - name: secret-postgres-creds
        secret:
          secretName: postgres-creds
          items:
          - key: password
            path: postgres-password
      - name: secret-redis-password
        secret:
          secretName: redis-password
          items:
          - key: redis-password
            path: redis-password
      - name: secret-session-encryption-key
        secret:
          secretName: session-encryption-key
          items:
          - key: password
            path: encryption-key
      - name: secret-storage-encryption-key
        secret:
          secretName: storage-encryption-key
          items:
          - key: password
            path: encryption-key
---
# Source: authelia/templates/traefikCRD/ingressRoute.yaml
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: authelia
  labels: 
    app.kubernetes.io/name: authelia
    app.kubernetes.io/instance: authelia
    app.kubernetes.io/version: 4.39.1
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: authelia-0.10.4
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`auth.lab53.net`) && PathPrefix(`/`)
    priority: 10
    middlewares:
      - name: chain-authelia
        namespace: authelia
    services:
      - kind: Service
        name: authelia
        port: 80
        namespace: authelia
        passHostHeader: true
        strategy: RoundRobin
        scheme: http
        weight: 10
        responseForwarding:
          flushInterval: 100ms
  tls:
    certResolver: letsencrypt
    domains:
      - main: auth.lab53.net
    options:
      name: authelia
      namespace: authelia
---
# Source: authelia/templates/traefikCRD/middlewares.yaml
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: forwardauth-authelia
  labels: 
    app.kubernetes.io/name: authelia
    app.kubernetes.io/instance: authelia
    app.kubernetes.io/version: 4.39.1
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: authelia-0.10.4
spec:
  forwardAuth:
    address: 'http://authelia.authelia.svc.cluster.local/api/authz/forward-auth'
    trustForwardHeader: true
    authResponseHeaders:
    - 'Remote-User'
    - 'Remote-Name'
    - 'Remote-Email'
    - 'Remote-Groups'
---
# Source: authelia/templates/traefikCRD/middlewares.yaml
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: chain-authelia-auth
  labels: 
    app.kubernetes.io/name: authelia
    app.kubernetes.io/instance: authelia
    app.kubernetes.io/version: 4.39.1
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: authelia-0.10.4
spec:
  chain:
    middlewares:
      - name: forwardauth-authelia
        namespace: authelia
---
# Source: authelia/templates/traefikCRD/middlewares.yaml
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: headers-authelia
  labels: 
    app.kubernetes.io/name: authelia
    app.kubernetes.io/instance: authelia
    app.kubernetes.io/version: 4.39.1
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: authelia-0.10.4
spec:
  headers:
    browserXssFilter: true
    customFrameOptionsValue: "SAMEORIGIN"
    customResponseHeaders:
      Cache-Control: "no-store"
      Pragma: "no-cache"
---
# Source: authelia/templates/traefikCRD/middlewares.yaml
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: chain-authelia
  labels:
    app.kubernetes.io/name: authelia
    app.kubernetes.io/instance: authelia
    app.kubernetes.io/version: 4.39.1
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: authelia-0.10.4
spec:
  chain:
    middlewares:
      - name: headers-authelia
        namespace: authelia
---
# Source: authelia/templates/traefikCRD/tlsOption.yaml
apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: authelia
  namespace: authelia
  labels: 
    app.kubernetes.io/name: authelia
    app.kubernetes.io/instance: authelia
    app.kubernetes.io/version: 4.39.1
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: authelia-0.10.4
spec:
  minVersion: VersionTLS12
  maxVersion: VersionTLS13
  cipherSuites:
  - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
  - TLS_RSA_WITH_AES_256_GCM_SHA384
