helmCharts:
  - name: authelia
    namespace: authelia
    includeCRDs: true
    releaseName: authelia
    version: 0.9.16
    valuesFile: values.yaml
    repo: https://charts.authelia.com
resources:
  - jwk-keypair.yaml
  - ldap-admin-secret-import.yaml