apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: immich-restore
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-admin-password
                  key: password
          volumeMounts:
            - mountPath: /mnt/pictures
              name: pictures
      volumes:
        - name: pictures
          persistentVolumeClaim:
            claimName: immich-restore-pvc