apiVersion: v1
kind: PersistentVolume
metadata:
  name: pictures-pv
  namespace: immich-restore
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.4.84
    path: /mnt/rpool/data/pictures
  storageClassName: nfs