apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-restore-pvc
  namespace: immich-restore
spec:
  resources:
    requests:
      storage: 1Ti
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  volumeName: pictures-pv