helmCharts:
  - name: traefik
    namespace: traefik
    includeCRDs: true
    valuesInline:
      logs:
        general:
          level: DEBUG
      certificatesResolvers:
        default:
          acme:
            httpChallenge:
              entryPoint: websecure
            email: aaron@kyriesenba.ch
            caServer: https://acme-staging-v02.api.letsencrypt.org/directory
    releaseName: traefik
    version: 34.3.0
    repo: https://traefik.github.io/charts
resources:
  - insecuretransport.yaml