helmCharts:
  - name: traefik
    namespace: traefik
    includeCRDs: true
    valuesFile: values.yaml
    releaseName: traefik
    version: 34.3.0
    repo: https://traefik.github.io/charts
resources:
  - insecuretransport.yaml
  - argocd-ingress.yaml