apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ default .Release.Name .Values.hostname }}.lab53.net`)
      kind: Rule
      services:
        - name: {{ .Release.Name }}
          {{- if .Values.serversTransport }}
          serversTransport: {{ .Values.serversTransport }}
          {{- end }}
          port: {{ .Values.container.port }}
  tls:
    certResolver: letsencrypt