{{- if .Values.secrets }}
{{- range .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
data:
  {{ $secretVal := printf "%s%s" (default "" .prefix) (randAlphaNum (default 32 (.length | int))) }}
  {{ .key }}: {{ $secretVal | b64enc | quote }}
{{- end }}
{{- end }}