apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: nextcloud-admin-creds
spec:
  secretTemplate:
    type: Opaque
    stringData:
      nextcloud-username: admin
      nextcloud-password: $(value)