# install: helm upgrade --install -n argocd --create-namespace -f argocd-values.yaml argocd argocd/argo-cd

global:
  domain: argocd.int.lab53.net

configs:
  cm:
    exec.enabled: true
  cmp:
    create: true
    plugins:
      ts:
        generate:
          command: ["bun", "run", "main.ts"]
        discover:
          fileName: main.ts
  params:
    server.insecure: true # This is the Argo project's recommendation for TLS termination at the Gateway level; terminate there, connect to Argo at :80.

repoServer:
  extraContainers:
    - name: ts-cmp
      command: ["/var/run/argocd/argocd-cmp-server"]
      image: oven/bun:1.3.11
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
      env: # This is required to allow Bun to install dependencies at a path it has write access to
        - name: BUN_INSTALL_CACHE_DIR
          value: /tmp
      volumeMounts:
        - mountPath: /tmp
          name: cmp-tmp
        - mountPath: /home/bun/app
          name: cmp-tmp
        - mountPath: /var/run/argocd
          name: var-files
        - mountPath: /home/argocd/cmp-server/plugins
          name: plugins
        - mountPath: /home/argocd/cmp-server/config/plugin.yaml
          name: argocd-cmp-cm
          subPath: ts.yaml
  volumes:
    - name: argocd-cmp-cm
      configMap:
        name: argocd-cmp-cm
    - name: cmp-tmp
      emptyDir: {}
