# To be placed in /var/lib/rancher/k3s/server/manifests. Auto-propagated to cluster at k3s startup.
# Required to configure Traefik, as the HelmChart resource is reset at each launch.

apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    service:
      annotations:
        kube-vip.io/loadbalancerIPs: 192.168.53.201
    providers:
      kubernetesGateway:
        enabled: true
    experimental:
      plugins:
        traefik-oidc-auth:
          moduleName: "github.com/sevensolutions/traefik-oidc-auth"
          version: "v0.19.0"
    gateway:
      enabled: false # Disable the default gateway - we manage a gateway w/ TLS settings in the traefik namespace
    ports:
      http:
        port: 80
        exposedPort: 80
        expose:
          default: true
      https:
        port: 443
        exposedPort: 443
        expose:
          default: true
      web:
        expose:
          default: false
      websecure:
        expose:
          default: false
