apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-cluster
  namespace: cnpg-system
spec:
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:14
  postgresql:
    shared_preload_libraries:
      - vectors.so
  bootstrap:
    initdb:
      postInitSQL:
        - ALTER SYSTEM SET search_path TO "$user", public, vectors;
        - CREATE EXTENSION IF NOT EXISTS "vectors";
  instances: 3
  storage:
    size: 10Gi