apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-cluster
  namespace: cnpg-system
spec:
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16-v0.3.0 # Immich requires pgvecto.rs < v0.4.0
  postgresql:
    shared_preload_libraries:
      - vectors.so
  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-user-creds
  managed:
    roles:
      - name: immich
        connectionLimit: -1
        ensure: present
        inherit: true
        login: true
        superuser: true # Immich requires superuser access for database administration and automatic backups
  instances: 3
  storage:
    size: 10Gi
