apiVersion: v1
data:
  username: aW1taWNoCg== # "immich" encoded in base64
kind: Secret
metadata:
  name: immich-user-creds
  labels:
    cnpg.io/reload: "true"
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
type: kubernetes.io/basic-auth