apiVersion: v1
stringData:
  username: immich
kind: Secret
metadata:
  name: immich-user-creds
  labels:
    cnpg.io/reload: "true"
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password
    reflector.v1.k8s.emberstack.com/reflection-allowed: true
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: immich
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: true
type: kubernetes.io/basic-auth