provider:
  name: aws

policy: sync
txtOwnerId: external-dns-ext-route53
sources: ["gateway-httproute"]
domainFilters: ["lab53.net"]
excludeDomains: ["int.lab53.net"]

env:
  - name: AWS_DEFAULT_REGION
    value: us-east-1
  - name: AWS_SHARED_CREDENTIALS_FILE
    value: /etc/aws/credentials

extraVolumes:
  - name: aws-credentials
    secret:
      secretName: external-dns-aws-credentials

extraVolumeMounts:
  - name: aws-credentials
    mountPath: /etc/aws
    readOnly: true

extraArgs:
  aws-zone-type: public
  gateway-name: traefik-external
  gateway-namespace: traefik
