apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-pv
  namespace: immich
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 192.168.4.84
    path: /mnt/rpool/data