apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-pvc
  namespace: immich
spec:
  resources:
    requests:
      storage: 500Gi
  storageClassName: nfs
  accessModes:
    - ReadWriteMany