env:
  DB_HOSTNAME: cnpg-cluster-rw.cnpg-system # Uses cluster DNS to resolve the RW service for Cloud Native Postgres
  DB_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: immich-user-creds
        key: password

immich:
  persistence:
    library:
      existingClaim: immich-pvc

image:
  tag: v1.129.0

redis:
  enabled: true