env:
  DB_HOSTNAME: immich-cluster-rw
  DB_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: immich-user
        key: password

immich:
  persistence:
    library:
      existingClaim: nas-volume-pvc

image:
  tag: v1.131.2

redis:
  enabled: true