server:
  cacheDir: /tmp
  database: /database/database.db
  sources:
    - path: "/data"
      config:
        defaultEnabled: true

auth:
  adminUsername: aaron
  methods:
    password:
      enabled: false
    proxy:
      enabled: true
      header: "Remote-User" # Automatically passed by Authelia
      createUser: true

userDefaults:
  darkMode: true
