server:
  cacheDir: /tmp
  database: /database/database.db
  internalURL: http://quantum
  sources:
    - path: "/data"
      config:
        defaultEnabled: true

auth:
  signup: false
  adminUsername: aaron
  methods:
    proxy:
      enabled: true
      header: "Remote-User"
      createUser: true

userDefaults:
  darkMode: true

integrations:
  office:
    url: https://onlyoffice.lab53.net
