server:
  baseURL: quantum.lab53.net
  cacheDir: /tmp
  database: /database/database.db
  externalURL: https://quantum.lab53.net
  internalURL: https://quantum.lab53.net
  sources:
    - path: "/data"
      defaultEnabled: true
      createUserDir: true

auth:
  signup: false
  methods:
    noauth: false
    proxy:
      enabled: true
      header: "Remote-User"
      createUser: true

userDefaults:
  darkMode: true