deployment:
  revisionHistoryLimit: 1

service:
#  externalIPs:
#    - 192.168.53.100
  spec:
    externalTrafficPolicy: Local

logs:
  access:
    enabled: true

persistence:
  enabled: true

providers:
  kubernetesCRD:
    allowCrossNamespace: true

ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.int.lab53.net`)
    entryPoints:
      - websecure
#    middlewares:
#      - name: forwardauth-authelia
#        namespace: authelia
