image:
  registry: hub.int.lab53.net/library

deployment:
  kind: DaemonSet

#service:
#  spec:
#    externalTrafficPolicy: Local # TODO: Figure out why this breaks things

experimental:
  plugins:
    traefik-oidc-auth:
      moduleName: github.com/sevensolutions/traefik-oidc-auth
      version: v0.15.0

logs:
  access:
    enabled: true

providers:
  kubernetesCRD:
    allowCrossNamespace: true
    allowExternalNameServices: true

ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.lab53.net`)
    entryPoints:
      - websecure

ports:
  web:
    transport:
      respondingTimeouts:
        readTimeout: 600s
        idleTimeout: 600s
        writeTimeout: 600s
  websecure:
    transport:
      respondingTimeouts:
        readTimeout: 600s
        idleTimeout: 600s
        writeTimeout: 600s