deployment:
  revisionHistoryLimit: 1

#service:
#  spec:
#    externalTrafficPolicy: Local # TODO: Figure out why this breaks things

logs:
  access:
    enabled: true

providers:
  kubernetesCRD:
    allowCrossNamespace: true
    allowExternalNameServices: true

ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.lab53.net`)
    entryPoints:
      - websecure
