driver: ldap
ldap:
  url: ldap://lldap.lldap:3890
  bind_user: uid=carpal,ou=people,dc=lab53,dc=net
  bind_pass: $(value)
  basedn: dc=lab53,dc=net
  filter: (uid=*)
  user_attr: uid
  attributes:
    - uid
    - mail
    - cn
  template: /etc/carpal/oidc.gotempl
