http:
  routers:
    pve:
      rule: Host(`pve.lab53.net`)
      service: pve
    truenas:
      rule: Host(`truenas.lab53.net`)
      service: truenas

  services:
    pve:
      loadBalancer:
        serversTransport: insecureTransport
        servers:
          - url: https://192.168.4.81:8006
    truenas:
      loadBalancer:
        serversTransport: insecureTransport
        servers:
          - url: https://192.168.4.84

  serversTransports:
    insecureTransport:
      insecureSkipVerify: true