apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-downloads-pvc
  namespace: transmission
spec:
  resources:
    requests:
      storage: 100Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  volumeName: transmission-downloads-pv