apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission-downloads-pv
  namespace: transmission
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.4.84
    path: /mnt/rpool/data
  storageClassName: nfs