apiVersion: v1
kind: Secret
metadata:
  name: postgres-admin-password
  namespace: troubleshooting
  labels:
    cnpg.io/reload: "true"
  annotations:
    secret-generator.v1.mittwald.de/autogenerate: password